### ISSUE TITLE
wallet connector gives error on localhost

### ISSUE THREAD

**Issue by Mik-A** [Cardano-Fans/crfa-public-webapp#21]
When clicking one of the wallets I get error. Copy from console
```
Error: window.cardano() is not injected by the user
    get wallet CardanoAPI.ts:28
    _callee$ Commands.ts:21
    Babel 20
    connectWallet useWallet.ts:40
    onClick SelectWalletModal.tsx:31
```

**Comment by SergeyShvager** [comment]
@Mik-A  Make sure that you have wallet browser extensions installed such as: ccvault, nami or yoroi. 
If they are not installed then window.cardano won't be injected by extensions

**Comment by Mik-A** [comment]
I do have Yoroi extension installed. In Firefox.
I will try installing extension on brave browser and see if that works.
However Firefox should not be neglected. The error prompt could be a bit more descriptive, I think

**Comment by Mik-A** [comment]
FYI I got it to work with ccVault and Brave. Firefox and Yoroi not

**Comment by Cardano-Fans** [comment]
@Mik-A if you got it to work with ccvault and Brave, can you submit PR fixing it if there were changes needed? Thank You!

**Comment by SergeyShvager** [comment]
Okay, sounds like extension code is executed after our code and therefore we need to have some `waitFor(window.cardano, callback)` mechanism

**Comment by SergeyShvager** [comment]
#25 I tried to add waitFor logic, lets check when it will go live

**Comment by Cardano-Fans** [comment]
It will go live this week for sure.

**Comment by matiwinnetou** [comment]
Can you verify now @Mik-A ?
