### ISSUE TITLE
Accessing NFT's owned by wallet

### ISSUE THREAD

**Issue by shaolinseed** [Cardano-Fans/crfa-public-webapp#24]
Hello, 

I have been looking through the code for a while now and struggling to find how to access other assets such as native tokens owned by the connected wallet. I need to validate a connected wallet owns a specific NFT and then grant them access to a certain page if they do, would you be able to point me in the right direction? 

Thank you so much !

**Comment by SergeyShvager** [comment]
@shaolinseed 
this method is used to check premium access:
https://github.com/Cardano-Fans/crfa-public-webapp/blob/main/features/wallet/useWallet.ts#L180

and token config is defined here:
https://github.com/Cardano-Fans/crfa-public-webapp/blob/main/shared/config.ts#L22

**Comment by shaolinseed** [comment]
Many thanks, very helpful!
